// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcq91X5h6RQ2UiCZEM9RnZH9LuqBa12pE',
    appId: '1:201962671792:web:71e7932edd869431e0f575',
    messagingSenderId: '201962671792',
    projectId: 'chat-d1607',
    authDomain: 'chat-d1607.firebaseapp.com',
    storageBucket: 'chat-d1607.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOcLm_bQWK6yyfCt_RGW4duF1p_6eLRNU',
    appId: '1:201962671792:android:887e2f5c59dee65de0f575',
    messagingSenderId: '201962671792',
    projectId: 'chat-d1607',
    storageBucket: 'chat-d1607.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2u5zn99Mbl4QvIohtkmuJKHB4mfEkjw8',
    appId: '1:201962671792:ios:8da9e6505a0ce1a3e0f575',
    messagingSenderId: '201962671792',
    projectId: 'chat-d1607',
    storageBucket: 'chat-d1607.appspot.com',
    iosClientId: '201962671792-1lkkiu68ljebocl75qinhf38gsk3butv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
